# write a python program to create an file with extension .txt to store frist user name , last user name , user age , user address , user university , user faculty , and at the end user male =>
creatFile = open("userInformationFile.txt" , "w+")
fristUserName = input("please enter the frist name of the user is : ")
creatFile . write("Your Frist Name Of The User Is : "+str(fristUserName)+"\n")
lastUserName = input("please enter the last name of the user is : ")
creatFile . write("Your Last Name Of The User Is : "+str(lastUserName)+"\n")
userAge = int(input("please enter the age of the user is : "))
creatFile . write("Your Age Of The User Is : "+str(userAge)+"\n")
userAddress = input("please enter the address of the user is : ")
creatFile . write("Your Addrees Of The User Is : "+str(userAddress)+"\n")
userUniversity = input("please enter the university of the user is : ")
creatFile . write ("Your University Of The User Is : "+str(userUniversity)+"\n")
userFaculty = input("please enter the faculty of the user is : ")
creatFile . write("Your User Faculty Of The User Is : "+str(userFaculty)+"\n")
userGender = input("please enter the gender of the user is : ")
creatFile . write("Your Gender Of The User Is : "+str(userGender)+"\n")
creatFile . close()